/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PayoutsRouteImport } from './routes/payouts'
import { Route as MultisigRouteImport } from './routes/multisig'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DepositsRouteImport } from './routes/deposits'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayoutsIdRouteImport } from './routes/payouts_.$id'
import { Route as CollectionsIdRouteImport } from './routes/collections_.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsRoute = PayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const MultisigRoute = MultisigRouteImport.update({
  id: '/multisig',
  path: '/multisig',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositsRoute = DepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsIdRoute = PayoutsIdRouteImport.update({
  id: '/payouts_/$id',
  path: '/payouts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIdRoute = CollectionsIdRouteImport.update({
  id: '/collections_/$id',
  path: '/collections/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/collections': typeof CollectionsRoute
  '/deposits': typeof DepositsRoute
  '/login': typeof LoginRoute
  '/multisig': typeof MultisigRoute
  '/payouts': typeof PayoutsRoute
  '/settings': typeof SettingsRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/payouts/$id': typeof PayoutsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/collections': typeof CollectionsRoute
  '/deposits': typeof DepositsRoute
  '/login': typeof LoginRoute
  '/multisig': typeof MultisigRoute
  '/payouts': typeof PayoutsRoute
  '/settings': typeof SettingsRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/payouts/$id': typeof PayoutsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/collections': typeof CollectionsRoute
  '/deposits': typeof DepositsRoute
  '/login': typeof LoginRoute
  '/multisig': typeof MultisigRoute
  '/payouts': typeof PayoutsRoute
  '/settings': typeof SettingsRoute
  '/collections_/$id': typeof CollectionsIdRoute
  '/payouts_/$id': typeof PayoutsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addresses'
    | '/collections'
    | '/deposits'
    | '/login'
    | '/multisig'
    | '/payouts'
    | '/settings'
    | '/collections/$id'
    | '/payouts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addresses'
    | '/collections'
    | '/deposits'
    | '/login'
    | '/multisig'
    | '/payouts'
    | '/settings'
    | '/collections/$id'
    | '/payouts/$id'
  id:
    | '__root__'
    | '/'
    | '/addresses'
    | '/collections'
    | '/deposits'
    | '/login'
    | '/multisig'
    | '/payouts'
    | '/settings'
    | '/collections_/$id'
    | '/payouts_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressesRoute: typeof AddressesRoute
  CollectionsRoute: typeof CollectionsRoute
  DepositsRoute: typeof DepositsRoute
  LoginRoute: typeof LoginRoute
  MultisigRoute: typeof MultisigRoute
  PayoutsRoute: typeof PayoutsRoute
  SettingsRoute: typeof SettingsRoute
  CollectionsIdRoute: typeof CollectionsIdRoute
  PayoutsIdRoute: typeof PayoutsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts': {
      id: '/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof PayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multisig': {
      id: '/multisig'
      path: '/multisig'
      fullPath: '/multisig'
      preLoaderRoute: typeof MultisigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposits': {
      id: '/deposits'
      path: '/deposits'
      fullPath: '/deposits'
      preLoaderRoute: typeof DepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts_/$id': {
      id: '/payouts_/$id'
      path: '/payouts/$id'
      fullPath: '/payouts/$id'
      preLoaderRoute: typeof PayoutsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections_/$id': {
      id: '/collections_/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressesRoute: AddressesRoute,
  CollectionsRoute: CollectionsRoute,
  DepositsRoute: DepositsRoute,
  LoginRoute: LoginRoute,
  MultisigRoute: MultisigRoute,
  PayoutsRoute: PayoutsRoute,
  SettingsRoute: SettingsRoute,
  CollectionsIdRoute: CollectionsIdRoute,
  PayoutsIdRoute: PayoutsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
